### Тестирование поиска оценок в дневнике по id
GET http://localhost:8000/assessmentReport?id=1

> {%
client.test("Тестирование возможности смотреть оценки по id",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

### Тестирование поиска оценок в дневнике по id занятия
GET http://localhost:8000/assessmentReport?lesson_id=1

> {%
client.test("Тестирование возможности смотреть оценки по lesson_id",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

### Тестирование поиска оценок в дневнике по id предмета
GET http://localhost:8000/assessmentReport?item_id=1

> {%
client.test("Тестирование возможности смотреть оценки по item_id",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

### Тестирование поиска оценок в дневнике по Названию предмета
GET http://localhost:8000/assessmentReport?item_name=Математика

> {%
client.test("Тестирование возможности смотреть оценки по item_name",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

### Тестирование поиска оценок в дневнике по расшифровке названия предмета
GET http://localhost:8000/assessmentReport?item_description=Математика

> {%
client.test("Тестирование возможности смотреть оценки по item_description",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

### Тестирование поиска оценок в дневнике по дате проведения занятия
GET http://localhost:8000/assessmentReport?lesson_date=2011.11.10 8:30

> {%
client.test("Тестирование возможности смотреть оценки по lesson_date",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

### Тестирование поиска оценок в дневнике по id преподавателя
GET http://localhost:8000/assessmentReport?teacher_id=1

> {%
client.test("Тестирование возможности смотреть оценки по teacher_id",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

### Тестирование поиска оценок в дневнике по ФИО преподавателя
GET http://localhost:8000/assessmentReport?teacher_fio=Круглова Наталия Сергеевна

> {%
client.test("Тестирование возможности смотреть оценки по teacher_fio",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

### Тестирование поиска оценок в дневнике по кабинету преподавателя
GET http://localhost:8000/assessmentReport?teacher_cabinet=56

> {%
client.test("Тестирование возможности смотреть оценки по teacher_cabinet",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

### Тестирование поиска оценок в дневнике по номеру и букве класса
GET http://localhost:8000/assessmentReport?class_number=6&class_letter=A

> {%
client.test("Тестирование возможности смотреть оценки по class_number&class_letter",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

### Тестирование поиска оценок в дневнике по id cтудента
GET http://localhost:8000/assessmentReport?student_id=1

> {%
client.test("Тестирование возможности смотреть оценки по student_id",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

### Тестирование поиска оценок в дневнике по ФИО cтудента
GET http://localhost:8000/assessmentReport?student_fio=Кузнецов Алексей Евгеньевич

> {%
client.test("Тестирование возможности смотреть оценки по student_fio",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

### Тестирование поиска оценок в дневнике по id родителей
GET http://localhost:8000/assessmentReport?parent_id=1

> {%
client.test("Тестирование возможности смотреть оценки по parent_id",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

### Тестирование поиска оценок в дневнике по ФИО родителей
GET http://localhost:8000/assessmentReport?parent_fio=Кузнецов Евгений Сергеевич

> {%
client.test("Тестирование возможности смотреть оценки по parent_fio",function (){
    client.assert(response.status===200, "Проверяю код ответа. Ожидаю код 200. Фактический код: "+response.status);
    client.assert(response.contentType.mimeType==="application/json", "Ожидаю application/json. Фактически: "+response.contentType.mimeType);
    client.assert(response.body[0]["id"]===1,"id оценок не корректен");
    client.assert(response.body[0]["lesson"]!==undefined,"Нет данных об занятии");
    client.assert(response.body[0]["lesson"]["id"]===1,"id занятия не корректен");
    client.assert(response.body[0]["lesson"]["item"]!==undefined,"Нет данных о предмете");
    client.assert(response.body[0]["lesson"]["item"]["id"]===1,"id предмета не корректен");
    client.assert(response.body[0]["lesson"]["item"]["name"]==="Математика","Название предмета не корректено");
    client.assert(response.body[0]["lesson"]["item"]["description"]==="Математика","Расшифровка предмета не корректено");
    client.assert(response.body[0]["lesson"]["date"]==="2011.11.10 8:30","Дата занятия не корректно");
    client.assert(response.body[0]["lesson"]["lessonDuration"]===40,"Продолжительность занятия не корректно");
    client.assert(response.body[0]["lesson"]["teacher"]!==undefined,"Нет данных о преподавателе");
    client.assert(response.body[0]["lesson"]["teacher"]["id"]===1,"id преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["fio"]==="Круглова Наталия Сергеевна","Фио преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["dateOfBirth"]==="1965.01.11","Дата рождения преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["phone"]==="89222444411","Номер телефона преподавателя не корректено");
    client.assert(response.body[0]["lesson"]["teacher"]["address"]==="ул. Ясная, д. 54, кв. 19","Адресс преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["cabinet"]===56,"Кабинет преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["teacher"]["email"]==="kruglova@gmail.com","email преподавателя не корректен");
    client.assert(response.body[0]["lesson"]["class"]!==undefined,"Нет данных о классе");
    client.assert(response.body[0]["lesson"]["class"]["id"]===3,"id класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["number"]===6,"Номер класса не корректен");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректена");
    client.assert(response.body[0]["lesson"]["class"]["letter"]==="А","Буква класса не корректен");
    client.assert(response.body[0]["student"]!==undefined,"Нет данных о студенте");
    client.assert(response.body[0]["student"]["id"]===1,"id студента не корректен");
    client.assert(response.body[0]["student"]["fio"]==="Кузнецов Алексей Евгеньевич","ФИО студента не корректен");
    client.assert(response.body[0]["student"]["dateOfBirth"]==="2011.01.11","Дата рождения студента не корректено");
    client.assert(response.body[0]["student"]["phone"]==="+792224444.88","Номер телефона студента не корректен");
    client.assert(response.body[0]["student"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс студента не корректен");
    client.assert(response.body[0]["student"]["parent"]!==undefined,"Нет данных о родителях Студента");
    client.assert(response.body[0]["student"]["parent"]["id"]===1,"id родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["fio"]==="Кузнецов Евгений Сергеевич","ФИО родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["dateOfBirth"]==="1975.10.01","Дата рождения родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["phone"]==="+79222444488","Номер телефона  родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["address"]==="ул. Казанская, д. 35Б, кв. 23","Адресс родителей не корректен");
    client.assert(response.body[0]["student"]["parent"]["placeOfWork"]==="ООО Алмаз","Место работы родителей не корректено");
    client.assert(response.body[0]["student"]["parent"]["email"]==="kuznecov@gmail.com","email родителей не корректен");
    client.assert(response.body[0]["mark"]===5,"Оценка не корректена");
});
 %}

###